const filterShortStateName = arr => arr.filter(str => str.length < 7)
const filterStartVowel = arr => arr.filter(str => /^[aeiou]/i.test(str))
const filter5Vowels = arr => arr.filter(str => (str.match(/[aeiou]/gi) || []).length >= 5)
const filterDistinctVowel = arr => arr.filter(str => new Set((str.match(/[aeiou]/gi) || []).map(v => v.toLowerCase())).size === 1)
const multiFilter = arr => arr.filter(obj => obj.capital.length >= 8 && !/^[ieaou]/i.test(obj.name) && /[aeiou]/i.test(obj.tag) && obj.region !== "South")